app/home/forms.py
#! -*- coding:utf-8 -*-
# Created by F1renze on 2018/3/18 13:54
__author__ = 'F1renze'
__time__ = '2018/3/18 13:54'

from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.ext.sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, Length, Regexp
from wtforms import ValidationError
from app import videos, images, cache
from app.models import Video, User, VideoTag

@cache.cached(key_prefix='query_factory')
def query_factory():
    return [t.name for t in VideoTag.query.all()]

class VideoUpload(FlaskForm):

    def get_pk(self):
        return self

    title = StringField(label='视频标题', validators=[DataRequired('标题不能为空!'),
                                                  Regexp("^(?!_)(?!.*?_$)[a-zA-Z0-9_\s\-\(\)\?\!\u4e00-\u9fa5]+$", 0,
                                                         '视频标题只能包含汉字, 数字, 空格, -, ?, !, 括号, 字母及下划线, 并且不能以下划线开头和结尾！'),
                                                  Length(1, 200)])
    video = FileField(label='视频文件', validators=[FileRequired('请上传视频文件!'),
                                              FileAllowed(videos, '不支持的视频格式!!')
                                                ])
    intro = TextAreaField(label='简介', validators=[DataRequired('简介不能为空!')])
    cover = FileField(label='封面', validators=[FileRequired('请上传封面!'),
                                              FileAllowed(images, '不支持的图片格式!!')])
    tag = QuerySelectField(label='视频分类', validators=[DataRequired()],
                           query_factory=query_factory, get_pk=get_pk)
    submit = SubmitField('上传', render_kw={
        'class': 'btn btn-primary form-control',
    })

    def validate_title(self, field):
        if Video.query.filter_by(title=field.data).first():
            raise ValidationError('视频标题已经被使用啦！')

class CommentForm(FlaskForm):
    content = TextAreaField(label='内容', validators=[DataRequired('请输入评论内容!')])
    submit = SubmitField('发表评论', render_kw={
        "class": "btn btn-secondary"
    })

class SearchForm(FlaskForm):
    search = StringField(validators=[DataRequired('搜索内容为空！'), Length(1, 64)],
                          render_kw={
                              'class': 'form-control',
                              'placeholder': 'Search'
                          })
    submit = SubmitField('搜索', render_kw={
        'class': 'btn btn-success'
    })

class EditProfileForm(FlaskForm):
    username = StringField(label='用户名',
                           validators=[DataRequired('用户名不能为空!'),
                                       Regexp("^(?!_)(?!.*?_$)[a-zA-Z0-9_\u4e00-\u9fa5]+$", 0,
                                              '用户名只能包含汉字, 数字, 字母及下划线, 并且不能以下划线开头和结尾！'),
                                       Length(1, 128)],
                           render_kw={
                               'class': 'form-control'
                           })
    avatar = FileField(label='用户头像', validators=[FileAllowed(images, '不支持的图片格式!!')],
                       render_kw={
                           'class': 'form-control'
                       })
    location = StringField(label='所在地', validators=[Length(1, 64)],
                           render_kw={
                               'class': 'form-control'
                           })
    phone = StringField(label='手机号码', validators=[DataRequired('请填写手机号码'),
                                                  Length(1, 11),
                                                  Regexp("^(13[0-9]|14[579]|15[0-3,5-9]|17[0135678]|18[0-9])\d{8}$", 0,
                                                         '请填写正确的手机号码格式！')],
                        render_kw={
                            'class': 'form-control'
                        })
    intro = TextAreaField(label='个人简介')
    submit = SubmitField('完成编辑', render_kw={
        'class': 'btn btn-primary form-control'
    })

    def __init__(self, user, *args, **kwargs):
        super(EditProfileForm, self).__init__(*args, **kwargs)
        self.user = user

    def validate_username(self, field):
        if field.data != self.user.username and User.query.filter_by(username=field.data).first():
            raise ValidationError('用户名已经被使用！')

app/home/__init__.py
#! -*- coding:utf-8 -*-
# Created by F1renze on 2018/3/18 13:52
__author__ = 'F1renze'
__time__ = '2018/3/18 13:52'

from flask import Blueprint

home = Blueprint('home', __name__)

from . import views, errors

app/home/views.py
#! -*- coding:utf-8 -*-
# Created by F1renze on 2018/3/18 13:54
__author__ = 'F1renze'
__time__ = '2018/3/18 13:54'

from . import home
from flask import render_template, flash, current_app, redirect, url_for, request, \
    abort
from flask_login import login_required, current_user
from app.home.forms import VideoUpload, CommentForm, SearchForm, EditProfileForm
from werkzeug.utils import secure_filename
from app.models import Video, Comment, User, UserLog, VideoTag, Admin
from app import db, cache
import os, uuid, stat
from datetime import datetime
from app import videos, images
from PIL import Image
from app.decorators import admin_required


@home.route('/')
# @cache.cached(30)
def index():
    # flash('欢迎!')
    page = request.args.get('page', 1, type=int)
    if Video.query.all() == None:
        pagination = None
        videos = None
    else:
        pagination = Video.query.order_by(Video.add_time.desc()).\
            paginate(page, per_page=current_app.config['INDEX_VIDEO_PER_PAGE'], error_out=False)
        videos = pagination.items
    tags = VideoTag.query.all()
    return render_template('home/index.html',
                           pagination=pagination, videos=videos, tags=tags)

@home.route('/tag/<tagname>')
@cache.cached()
def show_tag(tagname):
    page = request.args.get('page', 1, type=int)
    tag = VideoTag.query.filter_by(name=tagname).first()
    pagination = Video.query.filter_by(tag_id=tag.id).order_by(Video.add_time.desc())\
        .paginate(page, per_page=current_app.config['INDEX_VIDEO_PER_PAGE'], error_out=False)
    videos = pagination.items
    tags = VideoTag.query.all()
    return render_template('home/index.html', pagination=pagination,
                           videos=videos, tags=tags, active=tagname)

@home.route('/user/<username>')
def user(username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    newest_comments = user.comments[-2:]
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (user.videos.count() - 1) // current_app.config['SEARCH_PER_PAGE'] + 1
    pagination = user.videos.paginate(page,
                                      per_page=current_app.config['SEARCH_PER_PAGE'],
                                      error_out=False)
    return render_template('home/user.html', user=user, comments=newest_comments, pagination=pagination)

@home.route('/user/edit-profile', methods=['GET', 'POST'])
@login_required
def edit_profile():
    form = EditProfileForm(user=current_user)
    if form.validate_on_submit():
        if not os.path.exists(current_app.config['UPLOADS_DEFAULT_DEST']):
            os.makedirs(current_app.config['UPLOADS_DEFAULT_DEST'])
            os.chmod(current_app.config['UPLOADS_DEFAULT_DEST'],
                     stat.S_IRWXU + stat.S_IRGRP + stat.S_IWGRP + stat.S_IROTH)
        elif not os.path.exists(current_app.config['IMG_THUMB_DEST']):
            os.makedirs(current_app.config['IMG_THUMB_DEST'])
            os.chmod(current_app.config['IMG_THUMB_DEST'],
                     stat.S_IRWXU + stat.S_IRGRP + stat.S_IWGRP + stat.S_IROTH)

        if form.avatar.data:
            avatar_filename = images.save(form.avatar.data)
            size = 50, 50
            im = Image.open(os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'images/', avatar_filename))
            im.thumbnail(size)
            file_split_name = os.path.splitext(avatar_filename)
            img_thumb = file_split_name[0] + '_thumbnail' + file_split_name[-1]
            im.save(os.path.join(current_app.config['IMG_THUMB_DEST'], img_thumb))
            current_user.thumb_head_img = url_for('static', filename='uploads/thumbnails/' + img_thumb)
            current_user.head_img = images.url(avatar_filename)

        if form.location.data:
            current_user.location = form.location.data
        if form.phone.data:
            current_user.phone = form.phone.data
        if form.intro.data:
            current_user.info = form.intro.data
        current_user.username = form.username.data

        db.session.add(current_user)
        try:
            db.session.commit()
            flash('个人资料已经更新！')
        except:
            flash('未知错误！请重试或联系管理员')
            db.session.rollback()

        return redirect(url_for('.user', username=current_user.username))
    form.username.data = current_user.username
    form.phone.data = current_user.phone
    form.intro.data = current_user.info
    form.location.data = current_user.location
    return render_template('home/edit_profile.html', form=form, user=current_user)

@home.route('/user/collections/<username>')
@login_required
def display_collections(username):
    if current_user.username != username:
        abort(403)
    user = User.query.filter_by(username=username).first()
    if user is None:
        abort(404)
    page = request.args.get('page', 1, type=int)
    if page == -1:
        page = (user.collect_videos.count() - 1) // current_app.config['SEARCH_PER_PAGE'] + 1
    pagination = user.collect_videos.paginate(page,
                                              per_page=current_app.config['SEARCH_PER_PAGE'],
                                              error_out=False)
    return render_template('home/video_collections.html', user=user, pagination=pagination)

@home.route('/user/collections/uncollect/<int:id>')
@login_required
def user_uncollect(id):
    video = Video.query.get_or_404(id)
    current_user.uncollect(video)
    return redirect(url_for('home.display_collections', username=current_user.username))

@home.route('/video/delete/<int:id>')
@login_required
def delete_video(id):
    video = Video.query.get_or_404(id)
    name = video.title
    if current_user != video.uploader:
        abort(403)
    db.session.delete(video)
    video_file = os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'videos/', video.url)
    cover_file = os.path.join(current_app.config['UPLOADS_DEFAULT_DEST'], 'images/', video.cover)
    extension = os.path.splitext(video.cover)
    thumbnail_name = extension[0] + '_thumbnail' + extension[-1]
    thumbnail_file = os.path.join(current_app.config['IMG_THUMB_DEST'], thumbnail_name)
    try:
        if os.path.exists(video_file):
            os.remove(video_file)
        if os.path.exists(cover_file):
            os.remove(cover_file)
        if os.path.exists(thumbnail_file):
            os.remove(thumbnail_file)
    except:
        error_log = UserLog(user=current_user, ip=request.remote_addr, info='删除视频文件失败!')
        db.session.add(error_log)

    try:
        user_log = UserLog(user=current_user, ip=request.remote_addr, info='删除 '+video.title)
        db.session.add(user_log)
        db.session.commit()
        flash('视频[ ' + name + ' ]已经删除')
    except:
        flash('未知错误！请重试或联系管理员')
        db.session.rollback()
    return redirect(url_for('.user', username=current_user.username))

@home.route('/comment/delete/<int:id>')
@login_required
def delete_comment(id):
    comment = Comment.query.get_or_404(id)
    video_id = comment.video_id
    if current_user != comment.author:
        abort(403)
    db.session.delete(comment)
    try:
        db.session.commit()
        flash('评论删除成功')
    except:
        flash('未知错误！请重试或联系管理员')
        db.session.rollback()
    finally:
        return redirect(url_for('.video', id=video_id))

@home.route('/comment/disable/<int:id>')
@admin_required
def disable_comment(id):
    comment = Comment.query.get_or_404(id)
    video_id = comment.video_id
    comment.disabled = True
    db.session.add(comment)
    try:
        db.session.commit()
        flash('已经屏蔽此评论')
    except:
        flash('未知错误！')
        db.session.rollback()
    finally:
        return redirect(url_for('.video', id=video_id))

@home.route('/comment/enable/<int:id>')
@admin_required
def enable_comment(id):
    comment = Comment.query.get_or_404(id)
    video_id = comment.video_id
    comment.disabled = False
    db.session.add(comment)
    try:
        db.session.commit()
        flash('已经恢复此评论')
    except:
        flash('未知错误！')
        db.session.rollback()
    finally:
        return redirect(url_for('.video', id=video_id))

#视频收藏
@home.route('/video/collect/<int:id>')
@login_required
def video_collect(id):
    video = Video.query.get_or_404(id)
    if current_user.collect(video):
        # flash('视频收藏成功')
        return 'True:'+str(video.collecters.count())
    else:
        # flash('额, 发生未知错误, 请重试')
        return 'False:'+str(video.collecters.count())

@home.route('/video/uncollect/<int:id>')
@login_required
def video_uncollect(id):
    video = Video.query.get_or_404(id)
    if current_user.uncollect(video):
        # flash('视频已经从收藏中移除')
        return 'True:'+str(video.collecters.count())
    else:
        # flash('额, 发生未知错误, 请重试')
        return 'False:'+str(video.collecters.count())

@home.route('/video/like/<int:id>')
@login_required
def video_like(id):
    video = Video.query.get_or_404(id)
    ip = request.remote_addr
    if current_user.like(ip, video):
        return 'True:'+str(video.likers.count())
    else:
        return 'False:'+str(video.likers.count())

@home.route('/video/unlike/<int:id>')
@login_required
def video_unlike(id):
    video = Video.query.get_or_404(id)
    ip = request.remote_addr
    if current_user.unlike(ip, video):
        return 'True:'+str(video.likers.count())
    else:
        return 'False:'+str(video.likers.count())

@home.route('/video/<int:id>', methods=['GET', 'POST'])
def video(id):
    video = Video.query.get_or_404(id)
    form = CommentForm()
    if form.validate_on_submit():
        comment = Comment(content=form.content.data, video=video, author=current_user)
        db.session.add(comment)
        try:
            db.session.commit()
            flash('成功发布评论')
        except:
            flash('未知错误！请重试或联系管理员')
            db.session.rollback()

        return redirect(url_for('.video', id=video.id, page=-1))

app/templates/home/_comments.html
<ul class="commentList">
    {% for comment in comments %}
    <li class="item">
        <a href="{{ url_for('home.user', username=comment.author.username) }}">
            <img alt="评论者头像" width="40px" height="40px"
                 src="{% if comment.author.head_img %}{{ comment.author.thumb_head_img }}
            {% else %}{{ comment.author.gravatar(size=40) }}{% endif %}" class="rounded-circle avatar" style="border:1px solid #abcdef;">
        </a>
        <div class="comment-main">
            <div class="comment-header">
                <div class="comment-meta">
                    <a class="comment-author" href="user.html"><span class="text-primary">{{ comment.author.username }}</span></a>
                    <span>评论于</span>
                    <time title="{{ comment.add_time }}" datetime="{{ comment.add_time }}">{{ moment(comment.add_time, local=True).fromNow().format('L') }}</time>
                </div>
            </div>

            <div class="comment-body">
                {% if comment.disabled and current_user.is_admin %}
                <p>此评论因言论不当已被屏蔽</p>
                <hr>
                <p><i>{{ comment.content | safe }}</i></p>
                {% elif comment.disabled %}
                <p>此评论因言论不当已被屏蔽</p>
                {% else %}
                <p>{{ comment.content | safe }}</p>
                {% endif %}
                {% if comment.author == current_user and not current_user.is_admin %}
                <a href="{{ url_for('home.delete_comment', id=comment.id) }}"
                   class="btn btn-outline-danger float-right">删除评论</a>
                {% elif current_user.is_admin and comment.disabled %}
                <a href="{{ url_for('home.enable_comment', id=comment.id) }}"
                   class="btn btn-outline-danger float-right">恢复评论 [管理员]</a>
                {% elif current_user.is_admin %}
                <a href="{{ url_for('home.disable_comment', id=comment.id) }}"
                   class="btn btn-outline-danger float-right">屏蔽评论 [管理员]</a>
                {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>

app/templates/home/_pagination_macros.html
{% macro pagination_widget(pagination, endpoint, fragment='') %}

<ul class="pagination">
    <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
        <a class="page-link"
           href="{% if pagination.has_prev %}{{ url_for(endpoint, page=pagination.page - 1, **kwargs) }}
        {{ fragment }}{% else %}#{% endif %}">
            上一页
        </a>
    </li>

    {% for p in pagination.iter_pages() %}
    {% if p %}
    {% if p == pagination.page %}
    <li class="page-item active">
        <a class="page-link" href="{{ url_for(endpoint, page=p, **kwargs) }}{{ fragment }}">
            {{ p }}
        </a>
    </li>
    {% else %}
    <li class="page-item">
        <a class="page-link" href="{{ url_for(endpoint, page=p, **kwargs) }}{{ fragment }}">
        {{ p }}
        </a>
    </li>
    {% endif %}
    {% else %}
    <li class="page-item disabled">
        <a class="page-link" href="#">&hellip;</a>
    </li>
    {% endif %}
    {% endfor %}

    <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
        <a class="page-link"
           href="{% if pagination.has_next %}{{ url_for(endpoint, page=pagination.page + 1, **kwargs) }}
        {{ fragment }}{% else %}#{% endif %}">
            下一页
        </a>
    </li>
</ul>

{% endmacro %}

app/templates/home/index.html
{% extends 'home/base.html' %}

{% block title %}首页 -- CiliCili Video{% endblock %}

{% block styles %}
{{ super() }}
<link href="{{ url_for('static', filename='web/css/index.css') }}" rel="stylesheet"/>
<style>

.jumbotron {
    background: url("{{ url_for('static', filename='web/imgs/index.jpg') }}") no-repeat center center;
    height: 380px;
}

.card-body {
    position:relative;
}

.bar {
    position:absolute;
    right:5%;
    bottom:5%;
}

.bar img {
    weight:20px;
    height:20px;
}
</style>
{% endblock %}

{% block content %}
<div class="jumbotron jumbotron-fluid text-center">
    <div class="container-fluid">
        <h1 style="color:#fff;">CiliCili, 与你分享身边的美好</h1>
    </div>
</div>

<div class="container">
    {% if tags %}
    <nav class="navbar navbar-expand-sm bg-light">
        <ul class="navbar-nav">
            <li class="nav-item">
                {% if not active %}
                <a class="nav-link btn btn-outline-primary"
                   href="{{ url_for('home.index') }}">
                    首页
                </a>
                {% else %}
                <a class="nav-link" href="{{ url_for('home.index') }}">
                    首页
                </a>
                {% endif %}
            </li>
            {% for tag in tags %}
            <li class="nav-item">
                {% if tag.name == active %}
                <a class="nav-link btn btn-outline-primary"
                   href="{{ url_for('home.show_tag', tagname=tag.name) }}">
                    {{ tag.name }}
                </a>
                {% else %}
                <a class="nav-link" href="{{ url_for('home.show_tag', tagname=tag.name) }}">
                    {{ tag.name }}
                </a>
                {% endif %}
            </li>
            {% endfor %}
            <li class="nav-item"></li>
        </ul>
    </nav>
    <br>
    {% endif %}

    <div class="row">
        {% if videos %}
        {% for video in videos %}
        <div class="col-md-3">
            <div class="card text-center card-block">
                <img class="card-img-top" src="{{ url_for('static', filename='uploads/images/'+video.cover) }}"
                     alt="视频封面">
                <div class="card-body">
                    <h4 class="card-title">{{ video.title }}</h4>
                    <hr>
                    <a href="{{ url_for('home.video', id=video.id) }}" class="btn btn-info"
                       style="float:left;">播放</a>
                    <p class="bar">
                        <img src="{{ url_for('static', filename='web/icons/open.png') }}">&nbsp;&nbsp;&nbsp;
                        <small>{{ video.playnum }}</small>&nbsp;&nbsp;&nbsp;&nbsp;
                        <img src="{{ url_for('static', filename='web/icons/comments.png') }}">&nbsp;&nbsp;&nbsp;
                        <small>{{ video.comments.count() }}</small>
                    </p>
                </div>
                <div class="card-footer text-muted">
                    {{ moment(video.add_time, local=True).fromNow().format('L') }}
                </div>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <div class="col-md-12 text-center">
            <h3>
                暂时还没有视频呢, 登录后点击上方按钮上传视频
            </h3>
            <br>
            {% if not tags %}
            <a class="btn btn-dark text-light"
               href="{{ url_for('home.initialize') }}">
                初始化站点
            </a>
            {% endif %}
        </div>
        {% endif %}
    </div>
</div>

<p><br></p>
<div style="margin: 0px auto;display: table;">
    {% if pagination.items %}
        {% import 'home/_pagination_macros.html' as macros %}
        {% if not active %}
        {{ macros.pagination_widget(pagination, 'home.index') }}
        {% else %}
        {{ macros.pagination_widget(pagination, 'home.show_tag', tagname=active) }}
        {% endif %}
    {% endif %}
</div>
{% endblock %}

app/templates/home/user.html
{% extends 'home/base.html' %}

{% block styles %}
{{ super() }}
<style>
    body {
           background-color: #eee;
    }

    .info img {
        width:25px;
        height:25px;
    }

    .bar {
        width:20px;
        height:20px;
    }

</style>
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='web/css/comments.css') }}">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row">

        <div class="col-md-4">
            <div class="card">
                <img class="card-img-top rounded" src="{% if user.head_img %}{{ user.head_img }}
                {% else %}{{ user.gravatar(size=300) }}{% endif %}"
                     alt="用户头像">
                <div class="card-body rounded">
                    <h1 class="card-title"><b>{{ user.username }}</b></h1>
                    <p>
                        {% if user.info %}
                        {{ user.info | safe }}
                        {% else %}
                        Ta 很懒, 还没有填写个人信息呢~
                        {% endif %}
                    </p>
                    <hr>
                    <p class="info">
                        <img src="{{ url_for('static', filename='web/icons/location.png') }}">
                        &nbsp;
                        {% if user.location %}
                        {{ user.location }}
                        {% else %}
                        未知区域
                        {% endif %}
                    </p>
                    <p class="info">
                        <img src="{{ url_for('static', filename='web/icons/mail.png') }}">
                        &nbsp;
                        {% if user.email %}
                        {{ user.email }}
                        {% else %}
                        ???
                        {% endif %}
                    </p>
                    <p class="info">
                        <img src="{{ url_for('static', filename='web/icons/phone.png') }}">
                        &nbsp;
                        {% if user.phone %}
                        {{ user.phone }}
                        {% else %}
                        还未填写手机号码
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>

        <div class="col-md-8">
            <div class="card">
                <div class="card-header rounded" style="height:65px;">
                    <h4 class="text-center card-title">
                        用户资料
                        {% if current_user == user %}
                        &nbsp;
                        <a class="btn btn-primary" href="{{ url_for('home.edit_profile') }}">编辑</a>
                        {% endif %}
                    </h4>
                </div>
            </div>
            <!--text-light bg-secondary-->
            <table class="table table-secondary table-striped table-bordered table-hover">
                <tbody>
                <tr>
                    <td>注册时间</td>
                    <td>{{ moment(user.member_since, local=True).fromNow().format('L') }}</td>
                </tr>
                <tr>
                    <td>最后访问时间</td>
                    <td>{{ moment(user.last_visit, local=True).fromNow().format('L') }}</td>
                </tr>
                <tr>
                    <td>上传视频数</td>
                    <td>{{ user.videos.count() }}</td>
                </tr>
                <tr>
                    <td>评论数</td>
                    <td>{{ user.comments.count() }}</td>
                </tr>
                <tr>
                    <td>收到的赞数</td>
                    <td>
                        {% if user.count_like_num() %}{{ user.get_like_num }}
                        {% else %}
                        加载失败, 请刷新页面
                        {% endif %}
                    </td>
                </tr>
                </tbody>
            </table>

            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">最新评论</h4>
                </div>
                <div class="card-body">
                    {% if comments %}
                    <hr>
                    <ul class="commentList">
                        {% for comment in comments %}
                        <li class="item">
                            <a href="{{ url_for('home.user', username=comment.author.username) }}">
                                <img alt="评论者头像" width="40px" height="40px"
                                     src="{% if comment.author.head_img %}{{ comment.author.thumb_head_img }}
                                {% else %}{{ comment.author.gravatar(size=40) }}{% endif %}"
                                     class="rounded-circle avatar" style="border:1px solid #abcdef;">
                            </a>
                            <div class="comment-main">
                                <div class="comment-header">
                                    <div class="comment-meta">
                                        <a class="comment-author" href="user.html"><span class="text-primary">{{ comment.author.username }}</span></a>
                                        <span>评论于</span>&nbsp;
                                        <a href="{{ url_for('home.video', id=comment.video.id) }}">{{
                                            comment.video.title }}</a>
                                        &nbsp;
                                        <time title="{{ comment.add_time }}" datetime="{{ comment.add_time }}">{{
                                            moment(comment.add_time, local=True).fromNow().format('L') }}
                                        </time>
                                    </div>
                                </div>

                                <div class="comment-body">
                                    {% if comment.disabled %}
                                    <p>此评论因言论不当已被屏蔽</p>
                                    {% else %}
                                    <p>{{ comment.content | safe }}</p>
                                    {% endif %}
                                </div>
                            </div>
                        </li>
                        {% endfor %}
                    </ul>
                    {% else %}
                    <h3>暂时还没有评论呢~</h3>
                    {% endif %}
                </div>
            </div>

        </div>

        <p><br></p>

        <div class="col-md-12">


            <ul class="list-group">
                {% if pagination.items %}
                <li class="list-group-item list-group-item-light text-center">
                    <b>{{ user.username }}&nbsp;上传的视频</b>
                </li>
                {% else %}
                <li class="list-group-item list-group-item-info text-center">
                    <b>{{ user.username }}&nbsp;还没有上传过视频呢~</b>
                </li>
                {% endif %}
            </ul>
            <p></p>

            {% for video in pagination.items %}

            <div class="media rounded border border-info" style="padding: 10px;">
                <a class="mr-3" href="{{ url_for('home.video',id=video.id) }}">
                    <img width="150px" height="100px"
                         src="{{ url_for('static',filename='uploads/images/'+video.cover) }}"
                         alt="{{ video.title }}">
                </a>
                <div class="media-body">
                    <h4 class="mt-0">{{ video.title }}
                        <a href="{{ url_for('home.video', id=video.id) }}"
                           class="btn btn-primary float-right">
                            <span class="glyphicon glyphicon-play"></span>播放影片
                        </a>
                    </h4>
                    <span>{{ video.intro | safe }}</span>

                    {% if user == current_user %}
                    <!--不支持多模态-->
                    <div class="dropdown">
                        <button type="button"
                                class="btn btn-outline-danger dropdown-toggle float-right"
                                data-toggle="dropdown">删除
                        </button>
                        <div class="dropdown-menu">
                            <a class="dropdown-item active bg-danger"
                               href="{{ url_for('home.delete_video', id=video.id) }}">确认删除</a>
                            <a class="dropdown-item">取消</a>
                        </div>
                    </div>
                    {% else %}
                    <div class="float-right">
                        <img class="ml-3 rounded" height="40px" width="40px"
                             src="{% if video.uploader.head_img %}{{ video.uploader.thumb_head_img }}
                             {% else %}{{ video.uploader.gravatar(size=40) }}{% endif %}">
                        &nbsp;&nbsp;<b>{{ video.uploader.username }}</b>
                    </div>
                    {% endif %}

                    <img class="bar" src="{{ url_for('static', filename='web/icons/open.png') }}">&nbsp;&nbsp;&nbsp;
                    <small>{{ video.playnum }}</small>&nbsp;&nbsp;&nbsp;&nbsp;
                    <img class="bar" src="{{ url_for('static', filename='web/icons/comments.png') }}">&nbsp;&nbsp;&nbsp;
                    <small>{{ video.comments.count() }}</small>
                </div>
            </div>
            <p></p>
            {% endfor %}
        </div>

        {% if pagination.items %}
        <div class="mx-auto">
            {% import 'home/_pagination_macros.html' as macros %}
            <p><br></p>
            <div class="col-md-12">
                {{ macros.pagination_widget(pagination, 'home.user', username=user.username) }}
            </div>
        </div>
        {% endif %}


    </div>
</div>
{% endblock %}